import { ArrowUpRight } from "lucide-react";
import { works, experience, skills, subjects, interests, publication } from "@/data/redesign";
import { PROJECTS } from "@/data/portfolioData";
import type { ReactNode } from "react";
function Section({id,number,label,title,children}:{id:string;number:string;label:string;title:string;children:ReactNode}) {return <section id={id} className="section container"><div className="section-label"><span>{number} / {label}</span><h2>{title}</h2></div><div className="section-body">{children}</div></section>;}
function WorkLink({href,children}:{href:string|null;children:ReactNode}) {return href ? <a href={href}>{children} <ArrowUpRight size={13}/></a> : <span className="placeholder">{children} · link pending</span>;}
export default function PortfolioSections() {
 const extra = PROJECTS.filter(p => ["aadim-college-ai-chatbot","kritim-mind-tech-platform","mirayas-construction-platform","pahadi-research-cloud-platform"].includes(p.id));
 return <>
 <Section id="work" number="02" label="SELECTED PROJECTS" title="Selected Work"><p className="section-intro">Software built for use. Research grounded in real questions.</p>{works.map((work,i)=><article key={work.title} className="work-entry"><div className="work-heading"><span className="work-index">0{i+1}</span><div><p className="entry-type">{work.kind}</p><h3>{work.title}</h3></div></div><p>{work.description}</p><dl className="work-meta"><div><dt>Technology</dt><dd>{work.technology || "To be added"}</dd></div><div><dt>My role</dt><dd>{work.role}</dd></div></dl><div className="entry-links"><WorkLink href={work.url}>View Project</WorkLink><WorkLink href={work.github}>GitHub</WorkLink>{work.paper && <WorkLink href={work.paper}>Paper</WorkLink>}</div></article>)}<details className="additional-work"><summary>More engineering &amp; AI work <span>+</span></summary><div>{extra.map(p=><article key={p.id} className="extra-project"><h3>{p.title}</h3><p>{p.description}</p><p className="small-note">{p.tags.join(" · ")}<br/>My role: Software development</p><div className="entry-links"><WorkLink href={p.liveUrl || null}>View Project</WorkLink><WorkLink href={p.githubUrl || null}>GitHub</WorkLink></div></article>)}<p className="small-note">AI / NLP / Computer Vision collection: further project titles, descriptions, roles, and links to be added.</p></div></details></Section>
 <Section id="research" number="03" label="QUESTIONS & EXPLORATION" title="Research & Publications"><p className="lead">Making intelligent systems useful for learning.</p><p>My research interests center on language, retrieval, and education, with particular interest in AI that works for Nepali learners.</p><div className="interest-list">{interests.map(s=><span key={s}>{s}</span>)}</div><article className="publication"><p className="entry-type">JOURNAL ARTICLE · {publication.year}</p><h3>{publication.title}</h3><p className="authors">{publication.authors}</p><p><em>{publication.venue}</em><br/>{publication.pages} · {publication.year}</p><p>My first research journal publication, in AADIM Journal, explores a RAG-based approach to algorithm learning using Romanized Nepali and English. The work connects my interests in information retrieval, Nepali NLP, and AI for education.</p><div className="entry-links"><a href={publication.url}>Paper <ArrowUpRight size={13}/></a><a href={publication.url}>DOI: {publication.doi} <ArrowUpRight size={13}/></a><span className="placeholder">Code / Data · links pending</span></div></article></Section>
 <Section id="experience" number="04" label="PROFESSIONAL JOURNEY" title="Experience">{experience.map(e=><article className="experience-entry" key={e.company}><p className="entry-type">{e.period}</p><h3>{e.role}</h3><p className="organization">{e.company}</p><p className="location">{e.location}</p><ul>{e.points.map(p=><li key={p}>{p}</li>)}</ul></article>)}</Section>
 <Section id="teaching" number="05" label="SHARING KNOWLEDGE" title="Teaching & Mentoring"><p className="lead">Teaching is part of how I practice engineering.</p><p>As an adjunct lecturer, I help students connect computer science foundations with the software and intelligent systems they build. Teaching and mentoring are central to my professional identity.</p><p className="subjects-label">SUBJECTS I TEACH</p><ul className="subjects">{subjects.map(s=><li key={s}>{s}</li>)}</ul></Section>
 <Section id="education" number="06" label="ACADEMIC FOUNDATION" title="Education"><article className="education-entry"><p className="entry-type">GRADUATED 2023</p><h3>B.Sc. CSIT</h3><p className="organization">Tribhuvan University</p><p>Orchid International College</p><div className="academic-highlight"><p><strong>86%</strong><span>Overall percentage</span></p><p><strong>92.4%</strong><span>8th semester · TU Topper</span></p></div></article><article className="education-entry"><h3>+2 Science</h3><p>VS Niketan College · GPA: 3.63 / 4.00</p><p className="award">HISSAN Meritorious Student Award — 2019</p></article></Section>
 <Section id="skills" number="07" label="TOOLS OF THE TRADE" title="Technical Skills"><dl className="skills-list">{skills.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></Section>
 <Section id="entrepreneurship" number="08" label="BUILDING IN NEPAL" title="Entrepreneurship"><h3>Kritim Mind Technologies Pvt. Ltd.</h3><p>As CEO, I lead a company working across software, education technology, AI, and digital solutions. Kritim Guru brings that work into education through entrance preparation tools for students in Nepal.</p><a className="text-link" href="https://kritimguru.com">Explore Kritim Guru <ArrowUpRight size={14}/></a></Section>
 <Section id="achievements" number="09" label="MILESTONES" title="Achievements & Highlights"><ul className="highlights"><li><strong>Academic distinction</strong><span>B.Sc. CSIT — 86% overall; 8th semester — 92.4%, Tribhuvan University Topper.</span></li><li><strong>First journal publication</strong><span>Co-authored research published in AADIM Journal in 2026.</span></li><li><strong>Engineering, entrepreneurship &amp; education</strong><span>Software engineer, founder/CEO of Kritim Mind Technologies, and university lecturer.</span></li></ul></Section>
 </>;
}
